FROM ubuntu:22.04

RUN apt update \
    && apt upgrade -y \
    && apt install -y \
        build-essential \
        gdb \
        git \
        wget \
        vim \
    && apt clean all \    
    && echo 'Installing CMake from Kitware...' \
    && wget -q -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-Linux-x86_64.sh \
    && sh cmake-linux.sh -- --skip-license --prefix=/usr/local && rm cmake-linux.sh
